---
title: 'Chapter 8: Conclusions and future directions'
subtitle: "Synthesising insights from SNAP-2: EPICCS and further work"
author: "Danny Wong"
date: "15/10/2019"
csl: ../references/bib/the-lancet.csl
bibliography: ../references/bib/SNAP2.bib
link-citations: yes
description: "This is Chapter 7 of Danny's PhD Thesis"
output: 
  word_document:
    reference_docx: styles.docx
---

# Conclusions and future directions

```{r conclusions_setup, echo=FALSE, warning=FALSE, message=FALSE, results="hide", include=TRUE}
knitr::opts_chunk$set(echo = FALSE, dpi = 300)
options(scipen=2, digits=2)
```

## Summary of the thesis

Critical care is a complex medical intervention and admission to critical care following surgery is a component of the postoperative recovery pathway. The fundamental differences in structures and processes in critical care allow the delivery of higher levels of nursing and medical monitoring and therapies compared to general ward care, but consequently critical care is more costly and its availability is limited.

The scarcity of critical care beds, deficits in the accuracy of identifying patient risk, and equipoise over the efficacy of postoperative critical care have all been cited as reasons for the apparent misallocation of critical care resources seen in previous studies. 

In this thesis, I presented findings from the Second Sprint National Anaesthesia Project: EPIdemiology of Critical Care Provision (SNAP-2: EPICCS) study to (1) investigate the availability of postoperative critical care resources in the UK, Australia and New Zealand; (2) describe the risk profile and outcomes of patients undergoing inpatient surgery in these countries, and the proportions of patients admitted to critical care following their surgery; (3) assess how accurate clinicians are at evaluating patient mortality risk comparing their accuracy to available objective risk tools; and finally, (4) explore the factors which affect clinical decision-making around postoperative critical care. 

### Epidemiology of inpatient surgery and critical care admission

Patients who underwent surgery recruited to the SNAP-2: EPICCS cohort are likely to be a representative sample of the general population of surgical patients due to the non-consenting study methodology adopted. Using the data collected from this patient sample, the wider population of patients undergoing surgery could therefore be described. Patients undergoing a range of different surgical procedures, with differing surgical complexity and urgency were included in the cohort. The majority (more than two-thirds) of patients were either ASA-PS I or II patients, and the predicted mortality risks of the patients were low in general.

Approximately one in nine patients were admitted to critical care immediately after surgery, with the majority of them being planned admissions. About one out every 100 patients was admitted to critical care on a later date after surgery for treatment of complications. Only about a third of patients with mortality risks &ge;5% (predicted with P-POSSUM, SORT, or SRS) received immediate critical care admission. This finding was consistent across the three countries contributing data.

Postoperative mortality on the whole is low, the in-hospital mortality in this cohort was 1.2% at 30 days, and 1.4% at 60 days. Patients who were admitted to critical care immediately after surgery had higher mortality and morbidity rates, however the mortality rate for patients who were admitted to critical care later on during their hospital stay was higher still.

The median postoperative length of stay in hospital overall was 2 days, but lengths of stay generally varied according to surgical specialty, and were longer in patients admitted to critical care immediately after surgery (median 7 days). Approximately one in seven patients who underwent surgery with a planned overnight stay remained in hospital seven days following their procedure with some form of morbidity (as defined by POMS). Around two-thirds of patients who remained in hospital seven days after their surgery were found to suffer from POMS-defined morbidity. The incidence of POMS-defined morbidity was higher in patients who were directly admitted postoperatively to critical care (approximately 43%) than patients who were not directly admitted (approximately 10%).

The research questions introduced in *Chapter 1* will be revisited in the following sections to summarise the findings of this thesis.

### What is the availability of critical care, including high-acuity care areas?

Approximately 3% of all hospital beds in the UK, Australia and New Zealand are designated ICU or HDU beds, however notable differences in availability of postoperative critical care exist between the three country. UK hospitals had a lower median proportion of critical care beds compared to their counterparts in Australasia (2.7% in the UK vs 3.7% in Australia and 3.5% in New Zealand). When expressed in per capita terms, the UK had an estimated 9.3 critical care beds per 100,000 population, which was comparable to the estimate for New Zealand (9.1 beds per 100,000 population), while the estimate for Australia was higher (14.1 beds per 100,000 population) both other countries. These estimates update historical estimates from the literature, and demonstrate a trend of increasing per capita availability of critical care in these countries over approximately the last decade.

Approximately a third of hospitals in all three countries reported the use of high-acuity care areas which admitted higher-risk post-surgical patients unsuitable for the ward. On average, these high-acuity areas were small 4-bedded units with nursing ratios of one nurse to two patients. They were able to provide a heterogenous mix of postoperative monitoring and treatment modalities including continuous observations, invasive blood pressure monitoring, vasoactive infusions, etc.; almost half of them were managed by surgeons with no input from anaesthesia or intensive care specialists. Larger hospitals providing tertiary service were more likely to report using such high-acuity beds, suggesting that they are being used to augment the critical care capacity in hospitals where intensive care or high-dependency unit (ICU/HDU) bed capacity may be insufficient to support the volume of surgical activity.

When high-acuity areas and critical care beds are considered in total, the critical care capacity to support postoperative patient recovery is potentially increased.

### How do clinicians estimate postoperative risk, and how accurate are currently available prediction tools?

Patients undergoing surgery should ideally be risk-assessed prior to surgery, and although a number of objective risk tools are available for routine clinical use, the vast majority (over 80%) of clinicians used only subjective clinical assessment (either individual clinical judgement and/or ASA-PS grading) in estimating their patients' mortality risks preoperatively. 

When externally validating three objective risk tools (P-POSSUM, SORT and SRS) using the SNAP-2: EPICCS dataset, all three models showed good-to-excellent discrimination, with the best performing model, SORT, having an Area under the Receiver Operating Characteristic curve (AUROC) of 0.91. However, in terms of calibration, the objective risk tools all appeared to overestimate the probability of 30-day mortality, especially at the highest extremes of risk. 

In comparison, subjective clinical assessment appeared to discriminate high-risk from low-risk patient similarly well as the best-performing objective tool, with an AUROC of 0.89. Clinicians were also similarly overestimating risk when calibration curves were plotted.

A model incorporating information from both subjective clinical assessment and objective risk tools showed improved discrimination and calibration compared to subjective clinician assessments alone, suggesting that clinicians' subjective risk assessments may be further improved by combining information from objective risk tools. In addition to discrimination and calibration, combining information from both sources also results in improved predictions based on continuous net reclassification index, and decision curve analyses, suggesting that improved predictions have real-world clinical implications. A final model was presented which incorporated subjective clinical assessment and SORT variables performed the best out of all the models assessed and may play a role in clinical care in the future.

Taken together, there is little evidence to support the hypothesis that poor clinical risk assessment is a reason for poor identification of patients to refer to critical care admission, as the discrimination was high for all risk models (both subjective and objective), and the overestimation of risk identified in calibration analysis should result in more patients referred to critical care, not less.

### How do clinicians decide which patients to admit for postoperative critical care and what factors are influential?

Around one in ten patients had a perceived requirement for critical care admission by the perioperative team. These patients were more likely to be older, and have higher ASA-PS grades, and increased comorbidities. Substantial inter-hospital variation existed in the likelihood of patients being perceived to require critical care admission, and this variation persisted even after patient- and hospital-level variables were accounted for. 

Fixed-effects and mixed-effects logistic regression models showed that the factors which were most strongly associated with a critical care referral were high ASA-PS grades, higher complexity surgery, and emergency surgery. Increased critical care capacity, both in terms of day-to-day variation (expressed as the number of empty beds around the time of surgery), and general availability of critical care (expressed as a proportion of total hospital beds), were significantly associated with increased likelihood of recommendation, although the magnitude of this association was small in comparison with other factors. The likelihood of being recommended critical care admission was also strongly associated with surgical specialty &mdash; some specialties, such as orthopaedics and obstetrics, were highly unlikely to recommend critical care after accounting for patient risk factors compared with gastrointestinal surgery.

Once patients received a critical care recommendation, around three-quarters would then go on to be admitted to critical care, while only around 2% of those who did not receive a recommendation would be admitted. Unexpected intraoperative critical events and large volume blood loss were both associated with increased admission, for both patients recommended and not recommended critical care. Critical care bed capacity was not significantly associated with admission after critical care recommendation and other factors were taken into account. Substantial inter-hospital variation existed in the likelihood of admission despite accounting for other variables in the mixed-effects models.

## Other decisions around the time of surgery &mdash; whether to cancel

Much of the focus within this thesis has been predicated on the assumption that clinicians are limited to making a single dichotomous decision when faced with a high-risk patient, i.e. whether to admit the patient postoperatively to critical care or not. However, during the course of conducting this research, it became apparent from interactions with collaborators that there might be more complex decisions that could be made. Whether to cancel or delay surgery in the face of insufficient critical care capacity was often cited as an alternative option. Therefore, a planned analysis of SNAP-2: EPICCS data limited to UK hospitals was conducted looking at the incidences and reasons for on-the-day surgical cancellations [@wong_cancelled_2018]. 

In this analysis, approximately 10% of the UK patients who underwent surgery in SNAP-2: EPICCS reported a previous cancellation, while approximately 14% of patients who presented when the study was being conducted did not proceed with surgery on the day. Non-clinical reasons, predominantly inadequate bed capacity, accounted for a large proportion of previous cancellations. Independent risk factors for cancellation due to inadequate bed capacity included requirement for postoperative critical care (Odds Ratio [OR]: 2.92; 95% confidence interval [CI]: 2.12&ndash;4.02) and the presence of an emergency department in the treating hospital (OR:4.18; 95% CI: 2.22&ndash;7.89). Findings from this analysis attracted substantial media attention, including from general news outlets [@triggle_many_2018; @noauthor_one_2018; @denis_campbell_nhs_2018; @alex_matthews-king_one_2018; @torjesen_one_2018], and are likely to add weight to the policy discussions surrounding service planning in the future.

When combined with the other findings presented within this thesis, results from this analysis on surgical cancellations suggest that beyond information about patient-level risk factors, exogenous contextual factors like critical care availability and overall bed capacity exert an important effect on clinicians making decisions about their patients in the perioperative period.

## Outstanding questions and future directions

SNAP-2: EPICCS was a wide-ranging and ambitious observational study and its scope exceeded that of this PhD thesis. Research questions which remain that it may help to provide answers to include: 

1. How effective is postoperative critical care on patient outcomes after surgery?
2. What are the perceptions of clinicians towards critical care?
3. What are the long-term outcomes following surgery in both patients admitted and not admitted to critical care?

These outstanding questions will require long-term mortality outcomes to be obtained via linkage with administrative Hospital Episode Statistics and Office of National Statistics data in the future. Data linkage is currently underway and will constitute ensuing work beyond this PhD. Furthermore, within the programme of SNAP-2: EPICCS, data on clinician perceptions towards postoperative critical care were collected alongside the organisational survey and patient cohort studies, and will be reported elsewhere. The analyses of these residual components of SNAP-2: EPICCS will be conducted according to previously published analysis plans [@moonesinghe_snap-2_2017].

However, beyond the confines of observational research, the fundamental question of the effectiveness of critical care on postoperative outcomes may require the conduct of randomised controlled studies to completely remove the effects of confounding by indication, even with causal inference techniques like propensity score analysis and instrumental variable analysis. In this thesis, particularly in *Chapter 7*, we see that clinician perception of requirement for critical care is predictive of whether patients eventually get admitted. Three-quarters of the patients who were perceived to require critical care in the SNAP-2: EPICCS patient cohort ultimately received admission. This suggests that the clinician's opinions on whether patients should receive critical care are a strong confounder that may not be entirely adjusted for by statistical means. I personally believe that there is sufficient equipoise over the benefits of critical care, especially in the intermediate risk groups of between 5% and 10% predicted mortality, that it would be ethical to conduct such a randomised study in the future.

In this thesis, I have provided evidence for the increased accuracy that could be achieved through the combination of subjective and objective risk assessment information in determining an individual patient's risk. Future experimental studies using this combined approach to risk prediction to guide clinical interventions would likely be useful. With increased availability of cheap and accessible computing devices, clinical decision support aids may allow clinicians to augment their subjective opinions and arrive at better clinical decisions. There is observational evidence from the National Emergency Laparotomy Audit (NELA), that increased documentation of predicted patient mortality risks has been associated with increased consultant anaesthetist and surgeon presence during high-risk emergency surgery, and may also be correlated with improved national mortality outcomes over time [@nela_project_team_first_2015; @nela_project_team_second_2016; @nela_project_team_third_2017; @nela_project_team_fourth_2018; @eugene_development_2018]. It may very well be that through the routine use of combined risk prediction, more patients receive the correct intervention for them. 

Therefore, future randomised studies in this area may involve using a combined risk prediction approach to estimate patient mortality risks preoperatively, to identify patients in the intermediate risk group for which the benefits of critical care are less certain, and then to randomise them to receive critical care or enhanced care or ward-level care.

As critical care is expensive and resources are finite, there is a need for future health economic studies examining the cost effectiveness of managing postoperative patients in ICU/HDU as compared to admitting them onto general ward or enhanced care/high-acuity beds instead. With the imminent arrival of consensus definitions and regulations for enhanced care beds [@batchelor_critical_2017; @faculty_of_intensive_care_medicine_seeking_2019; @ficm__rcp_london_enhanced_care_working_parties_consultation_2019], more clarity surrounding the use of such facilities to manage high-risk patients will emerge, which will allow health economic analysis to become feasible.

There is a growing literature surrounding the phenomenon of Post-Intensive Care Unit Syndrome, i.e. the long-term symptoms and signs associated with survivors of critical illness [@jensen_impact_2015]. Much of this literature is related to the patients who have prolonged stays on ICU, with medical diagnoses and prolonged organ support. While the postoperative stays on critical care seen in the SNAP-2: EPICCS cohort were short (median 2 days, with an upper quartile of 5 days), a small proportion of patients would have had long stays on critical care, who might warrant future study using qualitative methods. It would be interesting to patients to guide their expectations about whether a small risk of developing clinically significant critical care complications is a worthwhile price to pay for the intended benefits of undergoing high-risk surgery. This would align closely with the recommendation issued by the Choosing Wisely UK Anaesthesia and Intensive Care Medicine that, *"All patients considering an operation should have shared decision-making consultations to discuss their individual chance of benefit or harm and to identify their personal preference"* [@santhirapala_choosing_2019].

Finally, in this thesis I have identified a small but significant effect of clinical resource availability affecting clinical decision-making. Clinician perceptions of the requirement for critical care, although largely influenced by patient risk factors, were subtly associated with the availability of critical care beds, both at the time of surgery and more generally within the institution as a proportion of overall hospital beds. Cancellations were also more likely to occur when there are competing demands for critical care beds. These findings should be used to prompt a more general discussion about healthcare resourcing and rationing going forward. With an increasingly frail and ageing world population [@kinsella_global_2005; @partridge_frailty_2012; @fowler_age_2019], and increasing burden of surgery into the future [@abbott_frequency_2017], more patients are likely to suffer complications from surgery. Frail older patients are more likely than younger, fitter patients to suffer from postoperative morbidity and mortality, but are less likely over the age of 75 to be admitted to critical care. As a society with finite means, we must discuss whether this is equitable. Policy makers must address this issue going forward.

## Conclusion

In this thesis, I have described current availability of postoperative critical care in the UK, Australia and New Zealand, and further identified and characterised the presence of high-acuity/enhanced care beds which may be used for high-risk patients recovering after surgery when formal critical care bed capacity may be insufficient. 

The risk profile of patients undergoing inpatient surgery in these three nations has been reported, and the accuracy of subjective clinician assessment of risk has been investigated, and compared with existing objective risk assessment tools. Only about a third of patients at high-risk of mortality following surgery, as defined using a range of predictive tools, are admitted to critical care, which is a lower proportion than is expected. The discrimination of clinicians' subjective assessments is comparable with the best performing objective risk tools, and clinician assessments are overly pessimistic. However, when information from both subjective risk assessment is combined with information from objective risk tools, the accuracy of predictions can be improved. In the combined predictive model reported, risk predictions are both statistically and clinically significant.

Finally, I described the factors which are strongly correlated with postoperative patients with a perceived requirement for and eventual admission to critical care. Although the availability of critical care beds has a marginal effect on decisions clinicians refer patients for critical care, this effect is small in comparison to patient risk factors for mortality, such as age, ASA-PS grade and the nature of the surgical insult. Once accounting for the perceived requirement for critical care, capacity is no longer significantly associated with eventual admission, and other factors such as intraoperative critical events and blood loss are more strongly correlated.

##### PAGE BREAK